### PR TITLE
Reporting STF Test Vectors (GP Section 11)

### PR DESCRIPTION
**Pull request by davxy**

### CODE REVIEW

**Comment by jaymansfield** [comment]
Hello. 

There is an issue in tiny/bad_validator_index-1 test. It doesn't seem to be testing for validator index like the full test does.

Tiny: "service_item_gas_too_low"
Full:  "bad_validator_index"

**Comment by jaymansfield** [comment]
One other to potentially take a look at:

Tiny vector "not_sorted_guarantor" is for some reason expecting a result of "duplicate_guarantors" but I can't seem to see any duplicates. Thanks!

**Comment by jaymansfield** [comment]
> @jaymansfield [fde23dd](https://github.com/w3f/jamtestvectors/commit/fde23dd28f1554cec34a02a602c3435a038f6cca)

Thank you.

Question about "too_high_work_report_gas" and "high_work_report_gas". Both of these have a work report with a gas of 1,000,000 which is larger then GA constant (100,000). Is 1,000,000 in both vectors a typo, was this meant to be 100,000 so that "high_work_report_gas" passes and "too_high_work_report_gas" fails?

**Comment by dakk** [comment]
How we can perform the check defined in 11.34 (v0.5.0 of gp) if the ancestors set (A) is not supplied?

**Comment by dakk** [comment]
> > Question about "too_high_work_report_gas" and "high_work_report_gas". Both of these have a work report with a gas of 1,000,000 which is larger then GA constant (100,000). Is 1,000,000 in both vectors a typo? Was this meant to be 100,000 so that "high_work_report_gas" passes and "too_high_work_report_gas" fails?
> 
> @jaymansfield
> 
> ~Looks like a typo. I'll push a fix~
> 
> Now that I double checked, I'm more incline thinking that may be a typo in the GP.
> 
> G T , representing the total across all cores, is 341,000,000, so it would make sense for G A to be below G T / 341 (to make space for the "always accumulate services" (as per def of G T ). However, if G A is 100,000, it is an order of magnitude lower than expected. Specifically, always accumulated services would have the following gas available: 314 , 000 , 000 − ( 341 ∗ 100 , 000 ) = 306 , 900 , 000 .
> 
> Have you tried asking in the chat?

This seems reasonable to me; I asked in GP chat

**Comment by dakk** [comment]
> 314 , 000 , 000 − ( 341 ∗ 100 , 000 ) = 306 , 900 , 000

This result is wrong; correct is 279900000

**Comment by davxy** [comment]
> > 314 , 000 , 000 − ( 341 ∗ 100 , 000 ) = 306 , 900 , 000
> 
> This result is wrong; correct is 279900000

The value is not 314,000,000 but 341,000,000 (there was a typo). The result remains unchanged:
341,000,000 - (341 * 100,000) = 306,900,000.

**Comment by yoyo2325** [comment]
Hi @davxy 
[anchor_not_recent-1.json](https://github.com/davxy/jam-test-vectors/blob/work-reports/reports/tiny/anchor_not_recent-1.json)

I don't think this will trigger the error
is your constant L = 8 ?

**Comment by bloppan** [comment]
Test service_item_gas_too_low is missing in README.md

**Comment by davxy** [comment]
Temporarily closed in favor of https://github.com/w3f/jamtestvectors/pull/28

**Comment by davxy** [comment]
> Hi @davxy [anchor_not_recent-1.json](https://github.com/davxy/jam-test-vectors/blob/work-reports/reports/tiny/anchor_not_recent-1.json)
> 
> I don't think this will trigger the error is your constant L = 8 ?

Why not? The report anchor is not in the state histrory

**Comment by davxy** [comment]
@dakk the work report gas issue should now being addressed both in the GP 0.5.2 and in these vectors. $G_A$ is now 10_000_000

**Pull request closed without merging**
