### PR TITLE
Codec vectors update

### PR DESCRIPTION
**Pull request by davxy**
### GP 0.4.*

- Added "segment root lookup" dictionary to "work report"
- WR "prerequisites" is now a set and not an option

### GP 0.5

- Add "exports count" to "work package spec"
- Extrinsic items order changed
- Add tickets entropy to epoch marker

### CODE REVIEW

**Comment by 0xjunha** [comment]
According to the set encoding rule in GP, it seems we don't have length discriminator.
In the test vector, `refine_context.bin` gives us:
```
0xc0564c5e0de0942589df4343ad1956da66797240e2a2f2d6f8116b5047768986f6967658df626fa39cbfb6014b50196d23bc2cfbfa71a7591ca7715472dd2b489329de635d4bbb8c47cdccbbc1285e48bf9dbad365af44b205343e99dea298f360751ab5b251361fbfd3ad5b0e84f051ccece6b00830aed31a5354e00b20b9ed2100000000
```
Shouldn't we remove the last 1 byte `0x00`?
It made sense when it was representing the old `Option::None`, but now I think we should remove it.

Maybe currently it is encoded following variable byte sequence encoding rather than set encoding, which also gives `0x00` for empty vec..

**Comment by 0xjunha** [comment]
In GP 0.5.0, extrinsics are encoded in the following order:
`tickets -> preimages -> guarantees -> assurances -> disputes`

While the test vector has:
`tickets -> disputes -> preimages -> assurances -> guarantees`

**Comment by davxy** [comment]
> According to the set encoding rule in GP, it seems we don't have length discriminator.

Are you talking about `prerequisites`?

**Comment by davxy** [comment]
> > Are you talking about `prerequisites`?
> 
> Yes!

As per eq.311, prerequisites requires length prefix.

**Comment by 0xjunha** [comment]
Ahh.. I missed it, my bad. Thanks for clarifying!

**Comment by davxy** [comment]
> In GP 0.5.0, extrinsics are encoded in the following order: `tickets -> preimages -> guarantees -> assurances -> disputes`
> 
> While the test vector has: `tickets -> disputes -> preimages -> assurances -> guarantees`

https://github.com/w3f/jamtestvectors/pull/19/commits/01528ae99f307279a13d9d05d3c492b73fc5e11b

**Comment by qiweiii** [comment]
seems epoch marker is missing the second entropy, in equation 5.10 (v0.5.0)

**Comment by davxy** [comment]
> seems epoch marker is missing the second entropy, in equation 5.10 (v0.5.0)

https://github.com/w3f/jamtestvectors/pull/19/commits/b00799a5299dd74f7646384f295e131109e3c106

**Comment by vekexasia** [comment]
I'm sorry 

> seems epoch marker is missing the second entropy, in equation 5.10 (v0.5.0)

but what second entropy are we talking about ? there is no second entropy in `He` in 5.10 for me (0.5.0).

**Comment by vekexasia** [comment]
> I'm sorry
> 
> > seems epoch marker is missing the second entropy, in equation 5.10 (v0.5.0)
> 
> but what second entropy are we talking about ? there is no second entropy in `He` in 5.10 for me (0.5.0).

Disregard all above. I somehow have a mid-0.5.0 (not tagged) without the second entropy.

**Pull request merged**
