### PR TITLE
Recent History STF Test Vectors (GP Section 7)

### PR DESCRIPTION
**Pull request by davxy**

### CODE REVIEW

**Comment by xlc** [comment]
I am not getting the same MMR hash. Can you clarify how it is calculated?
For `progress_blocks_history-2`, the payload is `0x8720b97ddd6acc0f6eb66e095524038675a4e4067adc10ec39939eaefc47d842` ++ `0x7507515a48439dc58bc318c48a120b656136699f42bfd2bd45473becba53462d` and the hash I am getting is `0x 7076c31882a5953e097aef8378969945e72807c4705e53a0c5aacc9176f0d56b`

I am getting the same number using https://emn178.github.io/online-tools/keccak_256.html with input of `8720b97ddd6acc0f6eb66e095524038675a4e4067adc10ec39939eaefc47d8427507515a48439dc58bc318c48a120b656136699f42bfd2bd45473becba53462d`

**Comment by davxy** [comment]
@xlc there was a deviation from the spec in our impl. Thank you

**Comment by xlc** [comment]
the values are matching with our implementation now 👍

**Comment by yoyo2325** [comment]
@davxy 
progress_with_bad_signatures-2.json this file will trigger two errors I think
in culprit "key": "0x3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29"
it's in the `pre_state`'s offender too
```
    --- FAIL: TestDisputesTiny/progress_with_bad_signatures-2.json (0.00s)
        disputes_test.go:139: Failed in File progress_with_bad_signatures-2.json
            except error Bad signature within the culprits sequence.
            failed to verify disputes: got Culprit offender already in the offenders list.
 ```

**Comment by davxy** [comment]
Temporarily closed in favor of https://github.com/w3f/jamtestvectors/pull/28

**Pull request closed without merging**
