### PR TITLE
Statistics STF Test Vectors (GP Section 13)

### PR DESCRIPTION
**Pull request by davxy**

### CODE REVIEW

**Comment by jaymansfield** [comment]
Post state tau does not get updated in these vectors. Can it be updated so that it matches the input slot #?

**Comment by davxy** [comment]
> Thank you for these.
> 
> In these vectors pre state tau and post state tau match. Can it be updated so that post state tau matches the input slot #?

This is intentional as is not duty of this subsystem STF to update Tau.

> Also there may be an issue in the epoch change vector. "guarantees" stats are all equal to zero even though it includes some in the input.

IIRC guarantees with keys from prev epoch are not included in the stats (as it uses keys from k'). But I need to double check

**Comment by davxy** [comment]
Temporarily closed in favor of https://github.com/w3f/jamtestvectors/pull/28

**Comment by davxy** [comment]
@jaymansfield  https://github.com/gavofyork/graypaper/issues/163

**Pull request closed without merging**
